/**
 * Preloaded Hackathon Demo Policies
 * Allows zero-network instant testing of the scanner across all 18 risk categories.
 */
window.TC_SAMPLE_POLICIES = [
  {
    "id": "high_risk_social",
    "title": "HyperNet AI Social & Cloud App Terms",
    "expected_risk": "CRITICAL RISK",
    "description": "High-exposure consumer policy with AI training, auto-renewal, third-party data sales, unilateral changes, and binding arbitration.",
    "content": "Welcome to HyperNet. By accessing or using our services, mobile application, or websites, you agree to be bound by these Terms of Service and Privacy Practices.\n\n1. DATA COLLECTION AND PERMISSIONS\nHyperNet reserves the right to collect sensitive personal data, including facial recognition scans, biometric templates, contact lists, and microphone audio. We collect information regarding your physical location even when the app is closed or operating in the background.\n\n2. SHARING AND THIRD-PARTY MONETIZATION\nWe may share your personal information with third parties, including advertising networks, commercial partners, and data brokers. In the event of a merger, acquisition, or sale, user data will be transferred to successor entities without additional notification.\n\n3. ADVERTISING, TELEMETRY AND AI MODEL TRAINING\nHyperNet utilizes device fingerprinting, session replay, and cross-site tracking pixels to deliver interest-based advertising. Furthermore, you grant HyperNet an irrevocable right to use your uploaded text, documents, photos, and voice data to train our artificial intelligence and machine learning models.\n\n4. CONTENT LICENSE AND INTELLECTUAL PROPERTY\nBy submitting photos, videos, or messages, you grant us a worldwide, perpetual, irrevocable, royalty-free license to reproduce, modify, publish, and sublicense your content for commercial purposes without attribution or compensation.\n\n5. SUBSCRIPTION AND RECURRING BILLING\nSubscriptions automatically renew at the current rate unless cancelled at least 48 hours prior to the renewal date. All payments and non-refundable fees will be charged to your payment method without additional authorization.\n\n6. UNILATERAL MODIFICATIONS\nWe reserve the right to modify these terms at any time at our sole discretion without prior notice. Your continued use of the service constitutes acceptance of all modified provisions.\n\n7. ACCOUNT TERMINATION\nWe may terminate or suspend your account at any time for any reason or for no reason, resulting in immediate forfeiture of all content and accrued credits without obligation to refund fees.\n\n8. DISCLAIMER OF WARRANTIES AND LIABILITY\nThe service is provided 'as is' and 'as available.' We disclaim all warranties of any kind. In no event shall the company be liable for any direct, indirect, incidental, or consequential damages resulting from data loss or security breaches.\n\n9. BINDING ARBITRATION AND CLASS ACTION WAIVER\nAll disputes shall be resolved exclusively through confidential binding arbitration rather than in court. You waive any right to a jury trial and agree to no class or representative actions against HyperNet."
  },
  {
    "id": "moderate_risk_saas",
    "title": "NovaDesk Cloud Workspace Agreement",
    "expected_risk": "CAUTION",
    "description": "A business SaaS platform with commercial auto-renewal, standard liability caps, unilateral maintenance windows, and telemetry.",
    "content": "NovaDesk Cloud Services Master Subscription Agreement.\n\n1. SCOPE AND SERVICES\nNovaDesk provides online collaboration software and secure workspace tools to authorized users subject to the provisions herein.\n\n2. DATA PRIVACY AND LOGGING\nWe collect telemetry data, diagnostic logs, and browser configuration information necessary to ensure operational reliability and deliver customer support. We do not sell your personal information to third parties.\n\n3. THIRD-PARTY SUB-PROCESSORS\nWe engage reputable cloud infrastructure vendors and payment processors to facilitate our service delivery. These sub-processors are bound by confidentiality obligations consistent with this agreement.\n\n4. SUBSCRIPTION BILLING AND AUTO-RENEWAL\nAnnual subscriptions renew automatically unless either party provides written notice of non-renewal at least 30 days prior to the expiration of the current subscription term. Fees paid are non-refundable except as explicitly stated in our Service Level Agreement.\n\n5. LIMITATION OF LIABILITY\nTo the maximum extent permitted by applicable law, NovaDesk's aggregate liability under this agreement shall not exceed the amount paid by customer in the twelve months preceding the incident. NovaDesk provides the platform as is with standard commercial performance warranties.\n\n6. TERMINATION AND SUSPENSION\nNovaDesk may suspend access if customer violates acceptable use policies or fails to settle outstanding balances within 15 days of formal notice. Upon formal account closure, NovaDesk will retain residual backup copies for up to 90 days to comply with regulatory retention mandates.\n\n7. AMENDMENTS\nWe may update these terms from time to time. If we make material modifications, we will provide 30 days advance notice via email or within the administrative console."
  },
  {
    "id": "safe_open_source",
    "title": "AegisGuard Privacy-First Client Terms",
    "expected_risk": "SAFE",
    "description": "Open-source zero-knowledge utility with end-to-end encryption, zero tracking, and no third-party sharing.",
    "content": "AegisGuard Terms of Use and Privacy Charter.\n\n1. ZERO KNOWLEDGE ARCHITECTURE\nAegisGuard operates as a local-first software utility. Your cryptographic keys, documents, and personal communications are encrypted on your device and are never transmitted to or readable by AegisGuard servers.\n\n2. NO TRACKING OR TELEMETRY\nWe do not use tracking cookies, device fingerprinting, analytics pixels, or session replay scripts. We do not collect location data, contact lists, or background sensor information.\n\n3. NO THIRD-PARTY SALE OR MONETIZATION\nWe do not sell, rent, monetize, or disclose personal data to advertisers, data brokers, or commercial third parties. No advertising networks are embedded in AegisGuard.\n\n4. USER OWNERSHIP AND RIGHTS\nYou retain 100% full ownership and intellectual property rights in all data, files, and content processed by the application. We claim no license, copyright, or ownership over your material.\n\n5. CANCELLATION AND EXPORT\nYou can export all your data in standard open formats at any time. Accounts can be terminated instantly with a single click, triggering immediate cryptographic erasure of any synced data.\n\n6. JURISDICTION AND DISPUTES\nAny disputes shall be resolved in ordinary civil courts having competent jurisdiction. We do not enforce mandatory binding arbitration or prohibit collective remedies."
  }
];
